### ISSUE TITLE
Recursive model

### ISSUE THREAD

**Issue by mflorczak** [asyncapi/java-spring-template#150]
#### Describe the bug
I want to create tree structure which each object has list of the same types.

#### How to Reproduce
This is my schemas components
![image](https://user-images.githubusercontent.com/36895020/126628591-8b13d61c-ce47-4be4-994e-7773f5637e8c.png)

It is recursive tree model
![image](https://user-images.githubusercontent.com/36895020/126628654-fd5fe6d6-43ed-4ec2-9e87-51d0136c8139.png)

And this is error
![image](https://user-images.githubusercontent.com/36895020/126628735-d1b708c8-eba6-49b4-844f-f3e68180f0df.png)

#### Expected behavior
As a user I want to be able to create recursive model eg. trees graphs etc.

**Comment by magicmatatjahu** [comment]
Problem is in https://github.com/asyncapi/java-spring-template/blob/master/filters/all.js#L101 line:

![image](https://user-images.githubusercontent.com/20404945/126645087-cf0657e2-8693-46a4-8620-5c0f1882d723.png)
