### ISSUE TITLE
Maven plugin to have the Java files generated automatically during build

### ISSUE THREAD

**Issue by karsai1993** [asyncapi/java-spring-template#175]
Hi,
Is there a maven plugin for this project that we could use? It would be great if we could use this project in our maven based spring boot application and we would like to generate the classes during a maven build, not manually.

#### Reason/Context
Please try answering few of those questions
- Why we need this improvement? To generate java files automatically during build, not manually.
- How will this change help? It would make the generation faster and smoother.
- What is the motivation? To be able to use a plugin that generates the files.

#### Description
Please try answering few of those questions
- What changes have to be introduced? I am not entirely sure.
- Will this be a breaking change? I don't think so.
- How could it be implemented/designed? 
1. Creating plugin that does the npm install and ag commands
2. Adding parameter options
3. Uploading the plugin in a public place

Best regards,
Laszlo

**Comment by Tenischev** [comment]
HI,
I dunno about such plugins, the best what I could suggest you for now is to use npm plugin to run async-api generator.

**Comment by derberg** [comment]
@Tenischev oh man, you are back 😁 

@karsai1993 as @Tenischev we always recommend use maven plugins for npm that allow you to run npm packages, so in theory, you could run generation this way in maven. I personally did not use it. @Pakisan did you have a chance to explore it, I think we talked some time ago about it, but I just don't remember, I'm getting old 😄
