### ISSUE TITLE
NPM certificate chain issue

### ISSUE THREAD

**Issue by karsai1993** [asyncapi/java-spring-template#176]
Hi,

#### Describe the bug

I am trying to run the command to generate the files:
`ag src/main/resource/asyncapi.yml -o target/asyncapi @asyncapi/java-spring-template`

But I get this error:
```
Something went wrong:
FetchError: request to https://registry.npmjs.org/@asyncapi%2fjava-spring-template failed, reason: self signed certificate in certificate chain
```

I even tried to `npm config set strict-ssl false` before running the above command but I got the same results.

Do you have any suggestions?

Best regards,
Laszlo

**Comment by derberg** [comment]
Hey, looks like it is related to your infrastructure, not this specific code generator. Have you tried https://stackoverflow.com/questions/34498736/npm-self-signed-cert-in-chain. Also, the alternative would be to use docker as described [here](https://github.com/asyncapi/generator#cli-usage-with-docker)

**Comment by derberg** [comment]
@karsai1993 hey, is this still a problem for you?

**Comment by karsai1993** [comment]
@derberg, well, we stopped checking this project. We need a maven plugin that does the generation for us.

**Comment by derberg** [comment]
@karsai1993 this is fine. If you do not need the issue, just close it.

And regarding maven, you can also close another issue. FYI I can tell you that people just use `exec-maven-plugin` and call cli directly, like call npm withing maven, example -> https://gist.github.com/phillipgreenii/7c954e3c3911e5c32bd0#file-pom-xml

**Comment by karsai1993** [comment]
Thank you for the suggestion.
