### ISSUE TITLE
Generated tests fail with "No such image: quay.io/testcontainers/ryuk:0.2.3"

### ISSUE THREAD

**Issue by shpelda** [asyncapi/java-spring-template#187]
#### Describe the bug
Generated tests fail when executed.

#### How to Reproduce
Execute the generator with some asyncapi.yaml, and run gradlew build of generated service.

#### Expected behavior
It should not fail.
[TEST-com.asyncapi.TestcontainerKafkaTest.zip](https://github.com/asyncapi/java-spring-template/files/7845230/TEST-com.asyncapi.TestcontainerKafkaTest.zip)

### How to fix
Updated dependencies of generated build.gradle:

```
--- a/build.gradle
+++ b/build.gradle
@@ -16,11 +16,11 @@ dependencies {
   implementation('org.springframework.kafka:spring-kafka')
   testImplementation('org.springframework.kafka:spring-kafka-test')
   testImplementation('junit:junit:4.12')
-  testCompile('org.testcontainers:kafka:1.14.1')
+  testCompile('org.testcontainers:kafka:1.15.1')
   implementation('com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider')
   implementation('com.fasterxml.jackson.datatype:jackson-datatype-jsr310')
     implementation('javax.validation:validation-api')
   implementation('org.springframework.boot:spring-boot-starter-integration')
   testImplementation('org.springframework.boot:spring-boot-starter-test')
-  testCompile('org.testcontainers:testcontainers:1.14.1')
+  testCompile('org.testcontainers:testcontainers:1.15.1')
 }

```

**Comment by Tenischev** [comment]
Hi @shpelda 
I can update, but most probably this would not help to you, because `quay.io/testcontainers/ryuk:0.2.3` is exist - https://quay.io/repository/testcontainers/ryuk?tag=latest&tab=tags 
Just for your info, this bug with `ryuk` image is appears time to time on testcontainers and seems there is no way for them to fix it 😄

**Comment by shpelda** [comment]
This update reproducibly helped on my machine. I do not understand the internals enough to argue and i am not blocked by this in any way now. So its up to your decision.
