### ISSUE TITLE
Don't generate AnonymousSchemaN classes for the payload

### ISSUE THREAD

**Issue by patrickuhlmann** [asyncapi/java-spring-template#203]
#### Reason/Context

When the Payload is directly specified for a message (instead of a reference, see below), The generated code should not contain a class that is called AnonymousSchema1.

Either the properties could be added directly to the class (in this example Song) or the Payload class could be named SongPayload. Otherwise the code is much harder to use.

#### Description

I used the following file:
```
asyncapi: 2.3.0
info:
  title: Record Label Service
  version: 1.0.0
  description: This service is in charge of processing music
servers:
  production:
    url: 'my-kafka-hostname:9092'
    protocol: kafka-secure
    description: Production Instance 1
    security:
      - myScram: []
channels:
  song.released:
    publish:
      message:
        $ref: '#/components/messages/song'
    subscribe:
      message:
        $ref: '#/components/messages/song'
components:
  securitySchemes:
    myScram:
      type: scramSha512
  messages:
    song:
      payload:
        type: object
        properties:
          title:
            type: string
            description: Song title
          artist:
            type: string
            description: Song artist
          album:
            type: string
            description: Song album
          genre:
            type: string
            description: Primary song genre
          length:
            type: integer
            description: Track length in seconds
```

And generated the code like this:
```
ag kafka-example.yml @asyncapi/java-spring-template -o ./output
```

This generated a class Song and a class AnonymousSchema1. I would have expected either one of:
- A class Song and a class SongPayload
- A class Song that contains the properties defined in the payload section directly.

**Comment by Tenischev** [comment]
Yeah... Unfortunately template just work with data provided by parser
@jonaslagoni this bug with Anonymous objects again
 related with https://github.com/asyncapi/parser-api/issues/34

**Comment by jonaslagoni** [comment]
Yea, it is definitely something we will have to address with the new parser implementation. 

Regardless of which implementation we end up with, I would highly recommend you explicitly set a unique identifier through either `$id` (not optimal) or `x-parser-schema-id` so the schema has a [unique identifier](https://github.com/asyncapi/parser-js/blob/fdee4882421a298ce298158e9ed65edb94a9acf6/lib/models/schema.js#L38) for tools @patrickuhlmann

**Comment by patrickuhlmann** [comment]
Thanks for the info ```x-parser-schema-id``` is a nice workaround.
