### ISSUE TITLE
Using Lombok instead of manually generated methods

### ISSUE THREAD

**Issue by patrickuhlmann** [asyncapi/java-spring-template#205]
#### Reason/Context

I noticed that in the generated code you have a "manually" generated setters/getters, equals, hashCode and toString method.

Did you ever consider to use Lombok? With Lombok you only need to set the annotations @ToString, @EqualsAndHashCode, @Getter and @Setter to get the same functionality which might make the template much simpler.

Furthermore also the @Builder annotation could be set to get a Builder.

**Comment by Tenischev** [comment]
Hi @patrickuhlmann 
It could be a good choice for someone. I think it is possible to add code generation with Lombok annotations as a template option(parameter), but "manual" way definitely will stay.  I believe that the decision to use Project Lombok in a code must be done by project stakeholders

**Comment by patrickuhlmann** [comment]
Hi @Tenischev 
I agree. I was more thinking about simplification of the code generation. Maybe the template could render the Lombok annotations (as they are simple to use/automate) and then run delombok (https://projectlombok.org/features/delombok) to let lombok generate the code for all the setters/getters. That way the final code would not have any lombok traces left while there is a solid implementation for Equals, HashCode and probably also a builder.
