### ISSUE TITLE
Fix invalid links in Markdown files

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/java-spring-template#221]
#### Reason/Context
We have recently started validating links in the markdown files across all of the repositories across the organization. 
As I can see in the [latest check](https://github.com/asyncapi/java-spring-template/runs/6243265229?check_suite_focus=true) by the time of writing this issue, there are some invalid links in some markdown files that need fixing.

#### How to fix the links
* Change `https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md` links in [README.md](https://github.com/asyncapi/java-spring-template/blob/master/README.md) file to `https://github.com/asyncapi/spec/blob/2.0.0/versions/2.0.0/asyncapi.md`

**Comment by Samridhi-98** [comment]
@KhudaDad414 I would like to work on it. 😊

**Comment by derberg** [comment]
@Samridhi-98 go ahead

**Comment by Samridhi-98** [comment]
I think this issue has been already resolved because I checked all links are working 😅😅

**Comment by derberg** [comment]
Yup, you are right https://github.com/asyncapi/java-spring-template/commit/2529d134009c82eb74c094ae8f595291ee4a180f
