### ISSUE TITLE
Java Spring code generator is not generating the correct deseriallizers

### ISSUE THREAD

**Issue by thiy** [asyncapi/java-spring-template#242]
Hi 

The Java Spring code generator is not generating the correct deseriallizers based on the given type.
it is always generating the IntegerDeserializer for key deseriallizer and JsonDeserializer for Value deseriallizer.

For example:

If I give the following 
publishSomeThing
      message:
        bindings:
          kafka:
            key:
              type: string
              enum: [ 'myKey' ]

It is generating 
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, IntegerDeserializer.class);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);

Looks like this config is hardcoded in partials/KafkaConfig.java

**Comment by coiouhkc** [comment]
Apparently https://github.com/asyncapi/java-spring-template/blob/902c0cf49410c9c011756cf1b5540b8b01c148d2/partials/KafkaConfig.java#L107 / https://github.com/asyncapi/java-spring-template/blob/902c0cf49410c9c011756cf1b5540b8b01c148d2/partials/KafkaConfig.java#L151 hard-code `IntegerSerializer.class`/`IntegerDeserializer.class`  not respecting the `key` of the kafka binding, see https://github.com/asyncapi/bindings/blob/master/kafka/README.md#message.
