### ISSUE TITLE
Maven Project 

### ISSUE THREAD

**Issue by waytoharish** [asyncapi/java-spring-template#268]
I am not able to find any template to generate the maven project instead of Gradle.
Is there any was to generate the Maven project ??

**Comment by Tenischev** [comment]
Hello @waytoharish 
Currently, unfortunately, no, only gradle build.
You are free to create Pull request with such changes :) 
Or if you find it possible suggest translation of current [build.gradle](https://github.com/asyncapi/java-spring-template/blob/master/template/build.gradle) to pom.xml and I'll do the rest

**Comment by waytoharish** [comment]
> Hello @waytoharish Currently, unfortunately, no, only gradle build. You are free to create Pull request with such changes :) Or if you find it possible suggest translation of current [build.gradle](https://github.com/asyncapi/java-spring-template/blob/master/template/build.gradle) to pom.xml and I'll do the rest

Thanks

**Comment by waytoharish** [comment]
What we can do is is create a pom.xml and pick up based on the user we can use build.gradle or pom.xml

**Comment by Tenischev** [comment]
Hello @waytoharish 
Now you could generate template with maven build, to do so, provide parameter `maven=true` in generator, e.g.
`asyncapi generate fromTemplate myAsynApi.yml @asyncapi/java-spring-template -o output-dir -p maven=true`
