### ISSUE TITLE
Support for java.math.BigDecimal 

### ISSUE THREAD

**Issue by ArturSydor** [asyncapi/java-spring-template#275]
#### Reason/Context
In java applications for working with decimal numbers we usually use java.math.BigDecimal, because double is not so accurate, but current generator version is not supporting this type. As workaround we can use String, but this requires additional conversation on java side. Would be very helpful to have BigDecimal as part of this generator.

**Comment by Tenischev** [comment]
Hello @ArturSydor 
for which type or format of parameter in AsyncApi you suggest to use BigDecimal?

**Comment by ArturSydor** [comment]
Hello @Tenischev 
i would suggest to use 
type: string
format: decimal

**Comment by Tenischev** [comment]
Hello @ArturSydor
Your feedback regarding PR #324 is welcome
