### ISSUE TITLE
Missing clientId in application.yml causing an error

### ISSUE THREAD

**Issue by VaishnaviNandakumar** [asyncapi/java-spring-template#293]
#### Describe the bug
When I first tried to clone and run the template I was stuck at the following issue.
`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'mqtt.broker.clientId' in value "${mqtt.broker.clientId}"`
This is caused due to a missing property in the application.yml file.
I wanted to know if there was a specific reason for excluding it. If there isn't, I would like to pick this issue up and contribute. 

#### How to Reproduce
-  `asyncapi generate fromTemplate asyncapi.yaml @asyncapi/java-spring-template -o spring-output-test`
-  Run application

#### Expected behavior
Spring boot application will not start.

**Comment by VaishnaviNandakumar** [comment]
@Tenischev @derberg  Hi, could you please take a look at this? Thanks

**Comment by derberg** [comment]
@Tenischev please have a look 🙏

**Comment by VaishnaviNandakumar** [comment]
@Tenischev Thank you. Will work on this and let you know once I've made a PR.
