### ISSUE TITLE
JavaBeans format for lists not compliant, causes failures with spring boot 3.0.2 when validation of list is added

### ISSUE THREAD

**Issue by jbiscella** [asyncapi/java-spring-template#296]
#### Describe the bug
When generating a list, the tool adds the suffix 'List', but Java Beans validation in spring boot 3.0.2 relies on full compliance to specifications by using reflection, then the name of fields and the getters should be aligned.
Current behaviour:
field: aliases
generated as: aliasesList
getter: getAliases
compliant to JavaBeans specs: no
 
Safe behavious
field: aliases
generated as: aliases
getter: getAliases
compliant to JavaBeans specs: yes

#### How to Reproduce
In spring boot 3.*, try to generate a kafka topic model with validation of a List annotated with @NotNull.
When validation will run, an IllegalStateException will be raised

#### Expected behavior
The field should be generated without the 'List' suffix in compliance with JavaBeans specification. 
( problem is at $$message$$ lines 42 and $$objectSchema$$ lines 24, 26,28,97,127,157,163,169 - I cannot contribute due to company policies )

**Comment by Tenischev** [comment]
Hi @jbiscella 
Thanks for the report! I will think what could be done (there was a reason to put `List` in the end)
