### ISSUE TITLE
Please add a parameter ( jakartaForKafkaValidation? ) to support both javax.validation and jakarta.validation packages 

### ISSUE THREAD

**Issue by jbiscella** [asyncapi/java-spring-template#297]
#### Reason/Context
While using the generator with spring boot 3.*, the imports will fail as the package javax.validation has been renamed to jakarta.validation

#### Description
Please try answering few of those questions
- What changes have to be introduced?
1. add the following code to the parameters of package.json (or pick a better naming): 
``` 
"jakartaForKafkaValidation": {
        "description": "To check if the target framework will leverage on javax.validation or jakarta.validation package for kafka",
        "default": "false",
        "required": false
      }
```
3. in $$message$$.java replace the import of javax.validation with
```
{% if params.jakartaForKafkaValidation === 'false' %}
import javax.validation.Valid;
{% else %}
import jakarta.validation.Valid;
{% endif %}
```
4. in $$onjectSchema$$.java replace the import of javax.validation with:
```
{% if params.jakartaForKafkaValidation === 'false' %}
import javax.validation.constraints.*;
import javax.validation.Valid;
{% else %}
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
{% endif %}
```

- Will this be a breaking change?
not with a safe default
- How could it be implemented/designed?
please see my previous answers: note that is an advise as I do not know in detail the templating engine. Sadly I cannot contribute due to company policies

**Comment by Tenischev** [comment]
Hello @jbiscella 
Thank you for the report! There is also some changes in spring-kafka 3.0 which is used together with spring-boot 3.0
