### ISSUE TITLE
Updating code for AMQP configuration

### ISSUE THREAD

**Issue by VaishnaviNandakumar** [asyncapi/java-spring-template#307]
Hi @Tenischev 
#### Reason/Context
I picked this up from the Missing Features list in the README. If no one has been assigned to this, I would like to pick it up.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Updating the AMQP config.java file in the existing template.
- How could it be implemented/designed?
This is an [example](https://github.com/Java-Techie-jt/springboot-rabbitmq-example) project that uses springboot with rabbitmq. If it looks good to you, I could use it as a reference for the updated config file. 
Some other references - 
https://spring.io/guides/gs/messaging-rabbitmq/
https://www.baeldung.com/spring-amqp

**Comment by Tenischev** [comment]
Hello @VaishnaviNandakumar 
If you could improve it, please go ahead. I didn't have enough real experience with amqp, so this point in readme was created.

**Comment by VaishnaviNandakumar** [comment]
Hi @Tenischev . Wanted to give you an update. I am making progress on this issue. Should be making a PR by the end of this week.
