### ISSUE TITLE
Add @Generated annotation to ease configuring tools for static code analysis

### ISSUE THREAD

**Issue by jbiscella** [asyncapi/java-spring-template#315]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
Many comnpanies run static code analysis tools to check code quality. Usually is good to have the @Generated annotation to programmatically exclude automatically generated code that could not be complaiant, despite still safe to be used.

- How will this change help?
Many tools can be configured to exclude classes annotated with https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html

- What is the motivation? 
See previous answers

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Add to any generated class the @Generated annotation

- Will this be a breaking change?
I feel not as that package should always be in the classpath in a spring boot project as far as I thing

- How could it be implemented/designed?
In the current template classes, add the @Generated annotation

**Comment by Tenischev** [comment]
@jbiscella your feed back for PR #323 are welcome.
