### ISSUE TITLE
Support parameter for channel

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#345]
#### Reason/Context
This is long missed feature of template to support [`parameter`s for channel object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#parametersObject).

#### Description
Support of `parameter`s should be introduced for all protocols currently supported by template (kafka, mqtt, amqp).
Changes required in following files:
- [AmqpPublisher.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/partials/AmqpPublisher.java)
- [KafkaPublisher.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/partials/KafkaPublisher.java)
- [MqttConfig.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/partials/MqttConfig.java)
- [MessageHandlerService.java](https://github.com/asyncapi/java-spring-template/blob/7053fd18445ed9ff63784816ec959b57bb958395/template/src/main/java/com/asyncapi/service/MessageHandlerService.java)

1. General support:
To support in kafka follow to reference doc, [RoutingKafkaTemplate](https://docs.spring.io/spring-kafka/docs/current/reference/html/#routing-template) to send, [containerFactory](https://docs.spring.io/spring-kafka/docs/current/reference/html/#record-listener) to receive.
To support in amqp follow to reference doc [topic exchange](https://www.cloudamqp.com/blog/part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html#topic-exchange)
To support in mqtt follow to reference doc, [topicExpression](https://docs.spring.io/spring-integration/api/org/springframework/integration/mqtt/outbound/AbstractMqttMessageHandler.html#setTopicExpression(org.springframework.expression.Expression)) to receive and send, to send MessageHandler also should be adopted.

3. Arbitrary methods
Parametrized methods should be provided, e.g. for channel `lights/{roomName}/{sensorID}` method like
```
public void <operationName>(String roomName, Integer sensorID, Message payload)
```

**Comment by AayushSaini101** [comment]
@Tenischev Can i take this

**Comment by Tenischev** [comment]
Hey @AayushSaini101 
This issue submitted for the Bounty program. So, I would prefer to wait end of submission period and election. If issue will be part of Bounty program, priorities of participants (if there will be a few) is follow:
```
1. AsyncAPI Maintainers (from any repository)

2. Regular contributors (GitHub users who have three or more Pull Requests merged throughout the AsyncAPI GitHub Organization)

3. Other (if a GitHub user doesn't fall under the above, the AsyncAPI Maintainer can determine the criteria i. e. regular volunteers, etc)
```

**Comment by AayushSaini101** [comment]
> Hey @AayushSaini101 This issue submitted for the Bounty program. So, I would prefer to wait end of submission period and election. If issue will be part of Bounty program, priorities of participants (if there will be a few) is follow:
> 
> ```
> 1. AsyncAPI Maintainers (from any repository)
> 
> 2. Regular contributors (GitHub users who have three or more Pull Requests merged throughout the AsyncAPI GitHub Organization)
> 
> 3. Other (if a GitHub user doesn't fall under the above, the AsyncAPI Maintainer can determine the criteria i. e. regular volunteers, etc)
> ```
Hi @Tenischev I have already contributed in Asyncapi these are my accepted MR https://github.com/asyncapi/cli/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed. Please let me know if i can work on this

**Comment by aeworxet** [comment]
Correct link would be
https://github.com/search?q=is%3Apr+author%3AAayushSaini101+org%3Aasyncapi+is%3Amerged
There are three merged pull requests throughout the AsyncAPI GitHub Organization, so @AayushSaini101 falls into the second category, and would be eligible to work on this issue if it gets selected for Bounty Program 2023-Q4 and there are no AsyncAPI Maintainers willing to take on it.

**Comment by Tenischev** [comment]
Since the second bounty task from this repo is closed, I would like to take on this one.

**Comment by aeworxet** [comment]
Bounty Issue's End Of Life (EOL): [2024-02-29 23:59:59 UTC-12:00](https://time.lol/#2024-02-29T23:59:59-12:00)

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Medium          |2023-11-07                 |2023-11-13              |**2023-12-22**        |2023-11-24         |2023-12-08         |**2023-12-22**|

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by aeworxet** [comment]
Please provide an update to the PR.

**Comment by Tenischev** [comment]
@aeworxet sorry, i underestimate the issue complexity. 
I would say currently issue implemented on 80% in draft PR, most complicated part is done.
I do my best to finish it on this working week.

**Comment by Tenischev** [comment]
@aeworxet PR ready for review
@derberg please 🙏

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

Please go to the [AsyncAPI's OpenCollective page](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the subject `Bounty java-spring-template#345`, tag `bounty`.

**Comment by aeworxet** [comment]
@asyncapi/bounty_team
