### ISSUE TITLE
Support traits

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#346]
#### Reason/Context
This is long missed feature of template to support `trait`s.

#### Description
Support of [operation](https://www.asyncapi.com/docs/reference/specification/v2.6.0#operationTraitObject) and [message](https://www.asyncapi.com/docs/reference/specification/v2.6.0#messageTraitObject) trait is required.
According to Spec, trait applied as [JSON Patch](https://datatracker.ietf.org/doc/html/rfc7386#section-2).

Probably, the better way to apply trait, is to create `generator:before` hook and compute result operation and message, so all other template generation will not be affected.

**Comment by AayushSaini101** [comment]
Hi @Tenischev For this issue, Do we need to generate the result the result in the particular file, or just need to update the java-spring-template to accept the fields for operation and message trait.

For example: 

`operationTraits:
     bindings:
       amqp:
        ack: false`

Do we need to generate the result somewhere in the src folder or just make the generator accept all these parameters? Thanks

**Comment by Tenischev** [comment]
@AayushSaini101 both. Template should support `trait`s by means, handle data from `trait`s correctly and generate output files taking into account data from `trait`s.

**Comment by AayushSaini101** [comment]
> @AayushSaini101 both. Template should support `trait`s by means, handle data from `trait`s correctly and generate output files taking into account data from `trait`s.

Thanks for the explanation

**Comment by jonaslagoni** [comment]
@Tenischev is this a bug you have found? In theory, generator should already have applied traits for you right? 🤔

**Comment by Tenischev** [comment]
@jonaslagoni you are right, it's my mistake I used a bit wrong API and encounter other not realized functionality of template and interpret it like a trait problem. My bad, this issue is not valid.
