### ISSUE TITLE
AmqpConfig.java file has syntax errors

### ISSUE THREAD

**Issue by xcspringwang** [asyncapi/java-spring-template#358]
#### Describe the bug
queues() method of AmqpConfig.java class missing a big parantheses "}"

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:
ag asyncapi.yaml  @asyncapi/java-spring-template 

- Screenshots
N/A
- Link to GitHub repository with project that has issues
https://github.com/asyncapi/java-spring-template/blob/master/partials/AmqpConfig.java

- Files that can help reproduce the issue, like your AsyncAPI file, either paste inside the issue in a code block or in a sharable [gist](https://gist.github.com/)
[report.pdf](https://github.com/asyncapi/java-spring-template/files/13578888/report.pdf)

#### Expected behavior
Fix the bug

**Comment by Tenischev** [comment]
Hello @xcspringwang 
Thank you for reporting, I'm aware of this bug, it will be fixed in https://github.com/asyncapi/java-spring-template/pull/352
