### ISSUE TITLE
Add all argument constructor to generated classes and make setters like a builder

### ISSUE THREAD

**Issue by vladigeras** [asyncapi/java-spring-template#368]
#### Reason/Context
Now generated classes have only one default no argument constructor and classic setters (set field value and return void). 
I suggest at least one changes: 
- add more constructor to generated classes: all argument constructor
- make setters like a builder (set field value and return this object)

This changes can increase readability of generated classes and decrease unnecessary verbose when using models in client services. 

#### Description
Add all argument constructor to generated classes OR (AND) make setters like a builder

**Comment by Tenischev** [comment]
Hello @vladigeras 
Thank you for the feedback.
I think it's also third option to use records.
About all argument constructor I see a drawback in readability when object has 10+ fields. Maybe argument constructor should be made for required fields.
Builder is also a good option.

I'll think about it

**Comment by vladigeras** [comment]
"About all argument constructor I see a drawback in readability when object has 10+ fields". 
Kotlin named arguments)). 

I suggest, that all argument constructor can be added as optional way to create an object. If it unsuitable way, then programmer can skip it and use another way. 

Can we use record for class generation now? For example, with some parameters
Use records = limit minimal Java version as 16
