### ISSUE TITLE
Add support of Kafka

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#6]
Current template is outdated (doesn't support api spec 2.0.0) and doesn't contain logic for Kafka generation.
It would be good to have a template for Kafka on Java based on AsyncAPI.
Also, perhaps supportedProtocols should be documented in configuration.

**Comment by derberg** [comment]
Hey @Tenischev. Thanks a lot for this issue. This template definitely needs some love so it is actually usable with 2.0.

I agree that [configuratio](https://github.com/asyncapi/java-spring-template/blob/master/.tp-config.json) should be done properly. If you will focus on Kafka support only please make sure to describe in contribution guide or somewhere else what are the extension points in the template that others could use to add support for other protocols

**Comment by Tenischev** [comment]
#7

**Comment by Tenischev** [comment]
released in #7
