### ISSUE TITLE
No source code generated when generation ran with a packageName starting with "com."

### ISSUE THREAD

**Issue by nicolas-soyeur** [asyncapi/java-spring-template#65]
Nothing is generated under src/main/java when I run the code generation with javaPackage starting with "com"

**for example this generate nothing :** 
ag -o testGeneration2 -p javaPackage=com.test ./src/main/resources/transaction-asyncapi.yaml @asyncapi/java-spring-template --force-write

**but these 2 run are working :** 
ag -o testGeneration2 -p javaPackage=com2.test ./src/main/resources/transaction-asyncapi.yaml @asyncapi/java-spring-template --force-write

ag -o testGeneration2 -p javaPackage=com2.com.test ./src/main/resources/transaction-asyncapi.yaml @asyncapi/java-spring-template --force-write

**Comment by nicolas-soyeur** [comment]
Maybe it is caused by this piece of code (in hooks/05_packageProcessor.js) : 

fs.removeSync(sourcePath + 'com');
fs.removeSync(testPath + 'com');

**Comment by nicolas-soyeur** [comment]
should be more efficient to do this instead ?

fs.removeSync(sourcePath + 'com/asyncapi');
fs.removeSync(testPath + 'com/asyncapi');

**Comment by Tenischev** [comment]
hey @nicolas-soyeur , thanks for the issue
Unfortunately, it's a bit more complicated. If we do
```
fs.removeSync(sourcePath + 'com/asyncapi');
fs.removeSync(testPath + 'com/asyncapi');
```
Then if it run as `-p javaPackage=org.test` the `com` package will stay at `src`

**Comment by Tenischev** [comment]
Hey @nicolas-soyeur , please have a look on #66

**Comment by nicolas-soyeur** [comment]
Hello @Tenischev , great thanks for this hot fix :). Great job
