### ISSUE TITLE
Doubts about code generated for streetlights.yaml

### ISSUE THREAD

**Issue by alberto1980** [asyncapi/java-spring-template#77]
I have some doubts about code generated with streetlights.yaml. There are some classes that I misunderstand

LightMeasured is a class that never is used in the generated code

On the other hand, handleReceiveLightMeasurement method at MessageHandlerService has this contract  public void handleReceiveLightMeasurement(**Message<?> message)**

shouldnt it be public void handleReceiveLightMeasurement(**Message<LightMeasuredPayload> message**) {  ???

PubishService Interface has methods like turnOn, turnOff, dimlight whose arguments are String instead of playLoad generated (TurnOnOffPlayload, DimLightPlayload). Is it right?

**Comment by Tenischev** [comment]
Hi @alberto1980 

Regarding `Message<?> message` it's just a good practice to show that class is parametrizable with Generic.

Regarding the generation itself. Message classes are not used at the moment, it is for the future when template will support headers and message traits. 

Also please check updated version of streetlights from the site. Soon PR will make template compatible with it.
