### ISSUE TITLE
Payload don't generated with avro schema

### ISSUE THREAD

**Issue by alberto1980** [asyncapi/java-spring-template#78]
Hi,

When I try to generate code with asyncapi specification with avro schema , payload class is not being generated.

I got classes references with names like AnonymousSchema5. Further, this class is not being generated

I have used 1.0.0-rc.7 generator version. 

Attach the asyncapi specification used
[asyncapi_kafka_avro.zip](https://github.com/asyncapi/java-spring-template/files/5047081/asyncapi_kafka_avro.zip)

**Comment by derberg** [comment]
@jonaslagoni what approach are you taking with the anonymous schemas in code generation? generating that as others, using anonymous schema id?

@alberto1980 try using here and in the other template a slightly different version of your file. Move payload schemas to `components.schemas` and in payload add `$ref` pointing to those schemas

**Comment by jonaslagoni** [comment]
@derberg  I use QuickType to handle the generation of schemas. Then there are some special cases that has to be managed i.e. root schema which had a `null` type.

**Comment by alberto1980** [comment]
@jonaslagoni how could I use the template to generate code with avro schema?

If move playload schemas to components.schemas I got errors like these:

**{
        "title": "/components/schemas/lightMeasuredPayload/type should be equal to one of the allowed values",
        "location": {
            "jsonPointer": "/components/schemas/lightMeasuredPayload/type",
            "startLine": 46,
            "startColumn": 7,
            "startOffset": 1212,
            "endLine": 46,
            "endColumn": 19,
            "endOffset": 1224
        }
    },**

@derberg commented me that this is not possible with components.schemas because custom schemas, other that asyncapi is not allowed there

If I use $ref with schema external reference, code generation is finished without errors but payload generated is not right. I got this generation for playload class

![image](https://user-images.githubusercontent.com/35599040/90121955-ebbd4180-dd5c-11ea-82b6-2bc52064cb33.png)

Attach asyncapi 
[kafka_avro_ref_external.zip](https://github.com/asyncapi/java-spring-template/files/5068395/kafka_avro_ref_external.zip)
yaml file

**Comment by jonaslagoni** [comment]
> @jonaslagoni how could I use the template to generate code with avro schema?

I am not sure the template currently supports the anonymous messages which it receives when being converted to a JSON draft 7 schema in the parser. This is because the template uses the `uid` of the schema and if none are sat, i.e. not being done by the avro parser, it receives this `anonymous` message id by the parser. So that behavior is correct. However it seems like the template does not generate the correct reference to the avro schemas somehow. **TLDR**: looks like the template does not atm. support avro schemas even though the underlying parser does. 


@alberto1980 can you add the document to a comment instead of a zip please, much easier 😄

**Comment by alberto1980** [comment]
Hi @jonaslagoni 

Add the document:

asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  production:
    url: kafka.bootstrap:{port}
    protocol: kafka
    variables:
      port:
        default: '9092'
        enum:
          - '9092'
          - '9093'

channels:
  event.lighting.measured:
    publish:
      bindings:
        kafka:
          groupId: my-group
      operationId: readLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        #$ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
        payload:
            $ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
    subscribe:
      operationId: updateLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        #$ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
        payload:
            $ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'


By the way, a topic that I forgot to comment on before. What is the meaning/use of the class LightMeasured that is being generated?. This class contains payload class but it never used in the generated code,

thanks

**Comment by jonaslagoni** [comment]
@alberto1980 no idea, @Tenischev maybe you can help out here :smile:

**Comment by derberg** [comment]
@alberto1980 please format this asyncapi file example with ``` (markdown syntax for code samples) so it has all the indentations needed for simple copy/paste.

**Comment by alberto1980** [comment]
Sorry, this is the formatted file

`asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  production:
    url: kafka.bootstrap:{port}
    protocol: kafka
    variables:
      port:
        default: '9092'
        enum:
          - '9092'
          - '9093'

channels:
  event.lighting.measured:
    publish:
      bindings:
        kafka:
          groupId: my-group
      operationId: readLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        #$ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
        payload:
            $ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
    subscribe:
      operationId: updateLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        #$ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
        payload:
            $ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'`

**Comment by alberto1980** [comment]
Sorry, this is the formatted file

```
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

servers:
  production:
    url: kafka.bootstrap:{port}
    protocol: kafka
    variables:
      port:
        default: '9092'
        enum:
          - '9092'
          - '9093'

channels:
  event.lighting.measured:
    publish:
      bindings:
        kafka:
          groupId: my-group
      operationId: readLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        #$ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
        payload:
            $ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
    subscribe:
      operationId: updateLightMeasurement
      message:
        schemaFormat: 'application/vnd.apache.avro;version=1.9.0'
        #$ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#'
        payload:
            $ref: 'https://raw.githubusercontent.com/alberto1980/apicurio-apis/master/schemas/external_avro_schema.json#' 
```

**Comment by Tenischev** [comment]
Hi all,
Ok, just simple test to have a look what template receives:
```
        const asyncapi = generator.asyncapi;
        for (let [key, schema] of asyncapi.allSchemas()) {
            console.error(key, schema);
        }
```
out:
```
<anonymous-schema-1> Schema {
  _json: { type: undefined, 'x-parser-schema-id': '<anonymous-schema-1>' }
}
<anonymous-schema-2> Schema {
  _json: { type: undefined, 'x-parser-schema-id': '<anonymous-schema-2>' }
}
```
I do not know what we could expect from this.

**Comment by derberg** [comment]
on a parser, we also support `$id` (https://github.com/asyncapi/parser-js/blob/master/lib/models/schema.js#L24) but I guess it is of no use in case we get avro that needs to be converted into json schema.

**Comment by Tenischev** [comment]
Hi @alberto1980,
After latest fix template AnonymousMessage classes are named correctly...
Regarding this reference to Avro schema, I tried to run it with local copy of your `external_avro_schema.json` and got the same result.
By the looking on `external_avro_schema.json` I see mostly only the `payloadExample` without any real definition of properties for message and so on. I'm not familiar with Avro schemas, so maybe I understand something wrong. 
But current template treats any `object` schema from AsyncAPI like a model class. This means that the content of your `external_avro_schema.json` was not reconsidered as `object` by parser... (As far as I could conclude)
@jonaslagoni , @derberg maybe you have ideas?

**Comment by derberg** [comment]
Yeap, I also think it is not a valid Avro schema. Valid example is https://github.com/asyncapi/avro-schema-parser/blob/master/tests/schemas/Person-1.9.0.avsc
