### ISSUE TITLE
Generated project does not compile

### ISSUE THREAD

**Issue by gerardbosch** [asyncapi/java-spring-template#79]
Hi! First of all thanks for working on developing a tooling around AsyncAPI 😃

The following report is **almost** identical of the one I've just opened here: https://github.com/asyncapi/java-spring-cloud-stream-template/issues/58

#### Describe the bug

When using the example reference AsyncAPI definition (https://bit.ly/asyncapi) which is using camelCase for schemas, the generated project is not Java compliant and hence does not build.

The generated model classes (the schemas) are in a file named in camelCase.java whilst the class definition itself is in PascalCase.
The above example results in:

  * File name: `dimLightPayload.java`
  * Class definition: `public class DimLightPayload`

Here is the console output:

```shell
$ gradle compileJava

> Task :compileJava
.../src/main/java/com/asyncapi/model/dimLight.java:6: error: class DimLight is public, should be declared in a file named DimLight.java
public class DimLight {
       ^
.../src/main/java/com/asyncapi/model/dimLightPayload.java:14: error: class DimLightPayload is public, should be declared in a file named DimLightPayload.java
public class DimLightPayload {
       ^
.../src/main/java/com/asyncapi/model/lightMeasured.java:6: 
error: class LightMeasured is public, should be declared in a file named LightMeasured.java
public class LightMeasured {
       ^
.../src/main/java/com/asyncapi/model/lightMeasuredPayload.java:14: error: class LightMeasuredPayload is public, should be declared in a file named LightMeasuredPayload.java
public class LightMeasuredPayload {
       ^
.../src/main/java/com/asyncapi/model/turnOnOff.java:6: error: class TurnOnOff is public, should be declared in a file named TurnOnOff.java
public class TurnOnOff {
       ^
.../src/main/java/com/asyncapi/model/turnOnOffPayload.java:14: error: class TurnOnOffPayload is public, should be declared in a file named TurnOnOffPayload.java
public class TurnOnOffPayload {
       ^
6 errors

> Task :compileJava FAILED
```

So the file name should be always switched to `PascalCase` as its being done with the class name itself (following Java conventions).

I've also find the problem in the section of messages:

```yaml
  messages:
    LightMeasured:
      name: lightMeasured
```

where the `name:` of the `message` is in `camelCase` and also generates files and classes in the same incorrect way.

One should argue that the definition of the official sample API could be updated to turn schema names into PascalCase to help align conventions. In my personal guideline I always define **schemas** in `PascalCase` and **parameters** in `camelCase`, which semantically maps to classes (or data models) and arguments of a function respectively (I guess in Java and probably many other languages). What do you think @fmvilas ?

But giving the above thought aside, the Java/Spring generator should handle the casing properly 😁  

#### How to Reproduce

```shell
npm install -g @asyncapi/generator
ag https://bit.ly/asyncapi @asyncapi/java-spring-template
gradle compileJava
```

#### Expected behavior

Let the generated code to compile out-of-the-box.

Thanks! 🙏 😃

**Comment by fmvilas** [comment]
You got me crazy here. I was looking at this issue and thought it was the other one, so was wondering where the heck is my comment 😄 

Similarly, I think this should be fixed on the template. Would you mind opening PRs?

**Comment by gerardbosch** [comment]
I'm not very sure if I will have time to inspect this in detail as to open a PR. For now I'm just testing the tooling and I faced this. Even I need to understand better the tech stack behind them. But in case I can have more spare time to invest or research in it I would like to do it. But honestly I don't think in this moment :-S

**Comment by fmvilas** [comment]
No problem, Gerard. Let us know if you start working on it. Just so we don't overlap. Thanks!

**Comment by Tenischev** [comment]
Hi @gerardbosch 
Could you please check one more time?
I run generation:
`docker run --rm -it -v $pwd/output:/app/output asyncapi/generator -o ./output https://bit.ly/asyncapi @asyncapi/java-spring-template --force-write`
and all files starts with capital leter:
![image](https://user-images.githubusercontent.com/4137916/94933824-989d7a80-04d3-11eb-9792-6f6525ba5051.png)

**Comment by gerardbosch** [comment]
Hi @Tenischev, I've just tried again and it works now! I'm not very sure what happened when I first tried or which template version was running.
I think you can close the issue :)
