### ISSUE TITLE
Support of opposite side application generation

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#8]
#### Reason/Context
As you know swagger allows to generate both server and client parts by one OpenAPI file. For sure, when we define "publish" and "subscribe" there is no clear "server" or "client". It is just about the application which could produce specified "subscribe" messages and consume specified "publish" messages.
Perhaps, generation of another side of communication makes sense. The application that could put messages to "publish" channel, so we could consume them, and read messages from "subscribe" channel.
At least this will be very fast way to create mock to test of main application.
Of course, there some obstacles e.g. for kafka the "groupId" binding is required to consume messages from topic. So, complete generation of "other" side could be not complete without modification of AsyncAPI spec file.

#### Description
The positive point, that in general to generate the opposite site application we should just switch "publish" to "subscribe" and vice-versa. 
Enabling of this mode could be done by flag for generator.

**Comment by MichaelDavisSolace** [comment]
I did this for the java-spring-cloud-stream template and the python template. I added a parameter called 'view' which can either be 'client', which conforms to the specification, or 'provider' which means that when you see 'subscribe' in the document you generate code that subscribes to topics. It would be nice if we were consistent. Maybe this could make it into the spec at some point.

BTW this feature also works with a specification extension 'x-view' on the info object.

**Comment by Tenischev** [comment]
@MichaelDavisSolace , as i described in description words as "client" or "server"(or "provider" in your case) couldn't be applied in case of AsyncAPI, from my point of view.

Also, i do not see a lot of sense to make this parameter `string`, which values you suppose except 'client' or 'provider'?

**Comment by damaru-inc** [comment]
Well, the terms 'view', 'client' and 'provider' were chosen by one of our senior architects at Solace, after many long discussions.  There has been a lot of debate about this issue between the AsyncAPI folk and us at Solace, and we have tried to hone our language to be as clear as possible. I don't think it would be easy for me to convince our team that we should change it.

As far as whether it's a string or not, command line parameters to the generator are always strings of course. The specification extension could be an enum, I don't know how much value that would add at this point.

**Comment by derberg** [comment]
looks like you guys have 2 fundamentally different solutions for common concern about the spec and I think it makes a lot sense to explore both to see which one plays better. For having support for `view` in the spec I recommend creating a feature request in asyncapi repo
