### ISSUE TITLE
Add support of channel parameters

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#93]
#### Reason/Context
Parameters in channel are widely used in `mqtt` or `amqp` protocols.

#### Description
Move channel names configuration to application properties.
Introduce parameter as an additional properties.
Result should be in re-usage of parameters like here https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-placeholders-in-properties

**Comment by derberg** [comment]
I think we just reopen whenever someone finds it and comments or maybe one of us finds time in the future to work on it
